version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: golang-postgres-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  app:
    build: .
    container_name: golang-app
    ports:
      - "8089:8089"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      
volumes:
  postgres-data: